// ---------- products.js ----------
// ✅ No "export", only plain JS variable (works in normal HTML setup)

const PRODUCTS = [
  {
    id: 1,
    name: "Rocket Lunic 2 Sound",
    brand: "Shivjothi",
    price: 179,
    quantity: "1 Box",
    image: "image/2 Sound Rocket.jpg",
    description: "High-flying colorful rocket bursting Two times with loud Sound",
    category: "Rockets",
  },
  {
    id: 2,
    name: "Rocket Music Whizling",
    brand: "Shri Vijai",
    price: 269,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "Large rocket with Whizling loud sound",
    category: "Rockets",
  },
  {
    id: 3,
    name: "Lunic Rocket 3 Sound",
    brand: "Nandi",
    price: 349,
    quantity: "1 Box",
    image: "image/24.jpg",
    description: "High-flying colorful rocket bursting Three times with loud Sound.",
    category: "Rockets",
  },
  {
    id: 4,
    name: "Lunic Rocket Jumbo Bome",
    brand: "Nandi",
    price: 249,
    quantity: "1 Box",
    image: "image/1004.jpg",
    description: "Rocket that whistles loudly before bursting.",
    category: "Rockets",
  },
  {
    id: 5,
    name: "Lunic Rocket Tuffan Queen",
    brand: "Nandi",
    price: 329,
    quantity: "1 Box",
    image: "image/29.jpg",
    description: "Sky rocket which is fly like a queen.",
    category: "Rockets",
  },
  {
    id: 6,
    name: "Lunic Rocket",
    brand: "Mugunth",
    price: 189,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "Spinning ground chakra with bright flames.",
    category: "Rockets",
  },
  {
    id: 7,
    name: "Rocket Bome Super",
    brand: "Vaishnavi",
    price: 139,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "it's make Loud Sound",
    category: "Rockets",
  },
  {
    id: 8,
    name: "Rocket Bome",
    brand: "Rajlakshmi",
    price: 110,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "Loud Sound",
    category: "Rockets",
  },
  {
    id: 9,
    name: "Lunic Rocket 3 Sound",
    brand: "Shivjothi",
    price: 199,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "Extra Loud which blast 3 times.",
    category: "Rockets",
  },
  {
    id: 10,
    name: "Flower Pot Small",
    brand: "Malti",
    price: 110,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Golden fountain with vibrant trails and sparkle.",
    category: "Anar",
  },
  {
    id: 11,
    name: "Flower Pot Big",
    brand: "Malti",
    price: 135,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Bright cone fountain spreading colorful sparks.",
    category: "Anar",
  },
  {
    id: 12,
    name: "Flower Pot Ashoka",
    brand: "Nandi",
    price: 399,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Multi-color fountain for evening display.",
    category: "Anar",
  },
  {
    id: 13,
    name: "Flower Pot Giant",
    brand: "Nandi",
    price: 549,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Star fountain with mixed color flames.",
    category: "Anar",
  },
  {
    id: 14,
    name: "Flower Pot Color koti",
    brand: "Mugunth",
    price: 259,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Small flower pot for kids with safe burning flame.",
    category: "Anar",
  },
  {
    id: 15,
    name: "Flower Pot Ashoka",
    brand: "Mugunth",
    price: 199,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Large flower pot with golden glitter and loud fizz.",
    category: "Anar",
  },
  {
    id: 16,
    name: "Flower Pot Special",
    brand: "Mugunth",
    price: 149,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Silver glittering fountain for Diwali celebrations.",
    category: "Anar",
  },
  {
    id: 17,
    name: "Flower Pot Special",
    brand: "Malti",
    price: 179,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Traditional sparkler stick for all ages.",
    category: "Anar",
  },
  {
    id: 18,
    name: "Flower Pot Red and Green",
    brand: "Malti",
    price: 279,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Long-lasting silver sparkler for festive fun.",
    category: "Anar",
  },
  {
    id: 19,
    name: "Flower Pot Colour koti",
    brand: "Malti",
    price: 439,
    quantity: "1 box",
    image: "image/21.jpg",
    description: "Bright neon sparkler with long-lasting glow.",
    category: "Anar",
  },
  {
    id: 20,
    name: "Flower Pot Red and White",
    brand: "Nandi",
    price: 279,
    quantity: "1 box",
    image: "image/120.jpg",
    description: "Small sound bomb with a sharp crack.",
    category: "Anar",
  },
  {
    id: 21,
    name: "Flower Pot Special",
    brand: "Nandi",
    price: 259,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Heavy sound bomb for extra thrill.",
    category: "Anar",
  },
  {
    id: 22,
    name: "Fuljhadi 9cm Two in One",
    brand: "Classic",
    price: 29,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Extremely loud thunder bomb for thrill-seekers.",
    category: "Fuljhadi",
  },
  {
    id: 23,
    name: "Fuljhadi 10cm",
    brand: "Classic",
    price: 59,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Stick firework releasing color flames.",
    category: "Fuljhadi",
  },
  {
    id: 24,
    name: "Fuljhadi 12cm",
    brand: "Classic",
    price: 69,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "Bright silver pencil for night celebrations.",
    category: "Fuljhadi",
  },
  {
    id: 25,
    name: "Fuljhadi 15cm",
    brand: "Classic",
    price: 79,
    quantity: "1 box",
    image: "image/27.jpg",
    description: "1 Box 10 pcs.",
    category: "Fuljhadi",
  },
  {
    id: 26,
    name: "Fuljhadi 30cm",
    brand: "Classic",
    price: 79,
    quantity: "1 box",
    image: "image/26.jpg",
    description: "1 Box 5 Pcs.",
    category: "Fuljhadi",
  },
  {
    id: 27,
    name: "Chakkar Deluxe",
    brand: "Blue Star",
    price: 239,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "Circular spinning firework with golden sparkle.",
    category: "Chakri",
  },
  {
    id: 28,
    name: "Chakkar Special",
    brand: "Blue Star",
    price: 129,
    quantity: "1 Box",
    image: "image/14.jpg",
    description: "Twisting fountain with bright spiral flames.",
    category: "Chakri",
  },
  {
    id: 29,
    name: "Chakkar Special",
    brand: "Nandi",
    price: 169,
    quantity: "1 Box",
    image: "image/13.jpg",
    description: "Sound bomb with a colorful burst before the boom.",
    category: "Chakri",
  },
  {
    id: 30,
    name: "Chakkar Ashoka",
    brand: "Standard",
    price: 149,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Chakri",
  },
  {
    id: 31,
    name: "Chakkar Ashoka",
    brand: "Standard",
    price: 149,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Chakri",
  },
  {
    id: 32,
    name: "Chakkar Duluxe",
    brand: "Nandi",
    price: 279,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Chakri",
  },
  {
    id: 33,
    name: "Ler (2000 Wala Ler)",
    brand: "Mugunth",
    price: 879,
    quantity: "1 Ler",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Ler",
  },
  {
    id: 34,
    name: "Ler (5000 Wala Ler)",
    brand: "Rajesh",
    price: 2199,
    quantity: "1 Ler",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Ler",
  },
  {
    id: 35,
    name: "Ler (1000 Wala Ler)",
    brand: "Ganesh Durve",
    price: 749, // corrected
    quantity: "1 Ler",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Ler",
  },
{
    id: 36,
    name: "Ler (16 Wala Ler)",
    brand: "Mugunth",
    price: 19,
    quantity: "1 Ler",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Ler",
  },
{
    id: 37,
    name: "Ler (300 Wala Ler)",
    brand: "Mugunth",
    price: 179,
    quantity: "1 Ler",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Ler",
  },

{
    id: 38,
    name: "30 Shot",
    brand: "Jawa",
    price: 879,
    quantity: "1 Box",
    image: "image/5.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 39,
    name: "12 Shot",
    brand: "Jawa",
    price: 269,
    quantity: "1 Box",
    image: "image/18.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 40,
    name: "7 Shot",
    brand: "Nandi",
    price: 159,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 41,
    name: "7 Shot Stalin",
    brand: "UV Box",
    price: 179,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 42,
    name: "12 Shot",
    brand: "Pravin",
    price: 329,
    quantity: "1 Box",
    image: "image/23.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 43,
    name: "Small Fancy 5 ka Dum",
    brand: "Blue Star",
    price: 299,
    quantity: "1 Box",
    image: "image/WhatsApp Image 2025-10-11 at 17.49.32_9dbce41e.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 44,
    name: "2 inch Fancy",
    brand: "Blue Star",
    price: 220,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 45,
    name: "2 inch Fancy",
    brand: "Jawa",
    price: 169,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 46,
    name: "1 inch Chota Fancy",
    brand: "Jawa",
    price: 89,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Shot",
  },
{
    id: 47,
    name: "2 inch Fancy 3D",
    brand: "Geeta Krishna",
    price: 329,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },

{
    id: 48,
    name: "2 inch Fancy 3 in 1",
    brand: "Aayan",
    price: 329,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },

{
    id: 49,
    name: "2 inch Fancy",
    brand: "Aayan",
    price: 110,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 50,
    name: "2 inch Fancy 3D",
    brand: "Blue Star",
    price: 659,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 51,
    name: "Chota Fancy 5 in 1",
    brand: "Blue Star",
    price: 549,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 52,
    name: "Small Fancy Astro Boy 5 in 1",
    brand: "Geet Krishna",
    price: 219,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 53,
    name: "60 Shot",
    brand: "Jawa",
    price: 1749,
    quantity: "1 Box",
    image: "image/7.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },

{
    id: 54,
    name: "15 Shot",
    brand: "NSV",
    price: 599,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 55,
    name: "15 Shot",
    brand: "Selon",
    price: 599,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 56,
    name: "3 inch Payli",
    brand: "NSV",
    price: 999,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 57,
    name: "4 inch Payli",
    brand: "NSV",
    price: 1299,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 58,
    name: "4 inch Payli",
    brand: "NSV",
    price: 1299,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 59,
    name: "Air Super Sonic Bome",
    brand: "Nandi",
    price: 159,
    quantity: "1 Box",
    image: "image/12.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 60,
    name: "Air Super Sonic Bome",
    brand: "Bandukwala",
    price: 159,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 61,
    name: "Mirchi Bome Super Duplex",
    brand: "Bandukwala",
    price: 239,
    quantity: "1 Box",
    image: "image/17.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 62,
    name: "Parrote Bome",
    brand: "Bandukwala",
    price: 69,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 63,
    name: "Laxmi Bome Medium Size",
    brand: "Nandi",
    price: 59,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 64,
    name: "Parrote Bome",
    brand: "ARD",
    price: 59,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 65,
    name: "Hathi Bome",
    brand: "Nandi",
    price: 79,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 66,
    name: "Two Sound Bome",
    brand: "Nandi",
    price: 79,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 67,
    name: "Two Sound Bome",
    brand: "ARD",
    price: 99,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 68,
    name: "Bullet Bome",
    brand: "Ganeshwari",
    price: 39,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 69,
    name: "Bullet Bome",
    brand: "Aman",
    price: 59,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 70,
    name: "King Kong",
    brand: "Nandi",
    price: 229,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 71,
    name: "Alwin Bome",
    brand: "Nandi",
    price: 199,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 72,
    name: "Commander Atom Bome",
    brand: "Jayhind",
    price: 219,
    quantity: "1 Box",
    image: "image/15.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 73,
    name: "Tehelka Atom Bome",
    brand: "Jayhind",
    price: 279,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 74,
    name: "Jolly Bome",
    brand: "Nandi",
    price: 259,
    quantity: "1 Box",
    image: "image/11.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 75,
    name: "Korona Bome",
    brand: "Aayan",
    price: 379,
    quantity: "1 Box",
    image: "image/10.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 76,
    name: "Red Bijali Loose ",
    brand: "Aman",
    price: 39,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "In 1 Pack 50 Pcs",
    category: "Child Items",
  },
{
    id: 77,
    name: "Red Bijali Loose ",
    brand: "Nandi",
    price: 59,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "In 1 Pack 50 Pcs",
    category: "Child Items",
  },
{
    id: 78,
    name: "Red Bijali Loose ",
    brand: "Aman",
    price: 49,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "In 1 Pack 100 Pcs",
    category: "Child Items",
  },
{
    id: 79,
    name: "Laxmi Bome Large Size",
    brand: "Nandi",
    price: 69,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 80,
    name: "Spring Gun",
    brand: "Matchbox",
    price: 49,
    quantity: "1 Pcs",
    image: "image/25.jpg",
    description: "Best Gun for Child",
    category: "Child Items",
  },
{
    id: 81,
    name: "Roll Gun",
    brand: "Roll",
    price: 20,
    quantity: "1 Pcs",
    image: "image/rollgun.jpg",
    description: "Best Gun for Child",
    category: "Child Items",
  },
{
    id: 82,
    name: "Small Missile Gun",
    brand: "Roll",
    price: 29,
    quantity: "1 Pcs",
    image: "image/Small Gun.jpg",
    description: "Best Gun for Child",
    category: "Child Items",
  },
{
    id: 83,
    name: "Big Missile Gun",
    brand: "Roll",
    price: 59,
    quantity: "1 Pcs",
    image: "image/smallgun.jpg",
    description: "Best Gun for Child",
    category: "Child Items",
  },
{
    id: 84,
    name: "Ler (28 Wala Ler)",
    brand: "Mugunth",
    price: 29,
    quantity: "1 Ler",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Ler",
  },
{
    id: 85,
    name: "Ring Cap",
    brand: "Sony",
    price: 15,
    quantity: "1 Pcs",
    image: "image/WhatsApp Image 2025-10-11 at 17.50.10_171766aa.jpg",
    description: "1 Pcs",
    category: "Child Items",
  },
{
    id: 86,
    name: "Mitthu Bome",
    brand: "Blue Star",
    price: 19,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Bome",
  },
{
    id: 87,
    name: "Mataka Genie",
    brand: "Timtim",
    price: 259,
    quantity: "1 box",
    image: "image/3.jpg",
    description: "Large flower pot with golden glitter and loud fizz.",
    category: "Anar",
  },
{
    id: 88,
    name: "Mataka Star Gudiya",
    brand: "Timtim",
    price: 299,
    quantity: "1 box",
    image: "image/2.jpg",
    description: "Large flower pot with golden glitter and loud fizz.",
    category: "Anar",
  },
{
    id: 89,
    name: "Mataka Mini Pearl Gudiya", // corrected typo
    brand: "Timtim",
    price: 259,
    quantity: "1 box",
    image: "image/WhatsApp Image 2025-10-11 at 17.53.42_8e84cbc6.jpg",
    description: "Large flower pot with golden glitter and loud fizz.",
    category: "Anar",
  },
{
    id: 90,
    name: "Rocket Baby Pearl",
    brand: "Rajlaxmi",
    price: 69,
    quantity: "1 Box",
    image: "image/16.jpg",
    description: "Large rocket with Whizling loud sound",
    category: "Rockets",
  },
{
    id: 91,
    name: "KitKat Silsil",
    brand: "Blue Star",
    price: 59,
    quantity: "1 Pack",
    image: ,
    description: "1 Pack",
    category: "Child Items",
  },
{
    id: 92,
    name: "KitKat Jee",
    brand: "Blue Star",
    price: 119,
    quantity: "1 Pack",
    image: "image/22.jpg",
    description: "1 Pack",
    category: "Child Items",
  },
{
    id: 93,
    name: "Roll",
    brand: "Gun Roll",
    price: 99,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "Gun Roll",
    category: "Child Items",
  },
{
    id: 94,
    name: "Missile",
    brand: "Gun Missile",
    price: 20,
    quantity: "1 Box 10 Unit",
    image: "/firecracker.webp",
    description: "Gun Missile 10 units",
    category: "Child Items",
  },
{
    id: 95,
    name: "Pop-Pop",
    brand: "Pop-pop",
    price: 10,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "1 Box",
    category: "Child Items",
  },
{
    id: 96,
    name: "Dhaga Bome",
    brand: "Fox",
    price: 10,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "1 Box",
    category: "Child Items",
  },
{
    id: 97,
    name: "Machis Bome",
    brand: "Fox",
    price: 20,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "1 Box",
    category: "Child Items",
  },
{
    id: 98,
    name: "Photo Flash",
    brand: "Blue Star",
    price: 110,
    quantity: "1 Box",
    image: "image/20.jpg",
    description: "1 Box",
    category: "Fancy Items",
  },
{
    id: 99,
    name: "Pencile Golden Light",
    brand: "Blue Star",
    price: 59,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "1 Box",
    category: "Fancy Items",
  },
{
    id: 100,
    name: "Pencile Golden Light",
    brand: "VKR",
    price: 69,
    quantity: "1 Box",
    image: "image/19.jpg",
    description: "1 Box",
    category: "Fancy Items",
  },
{
    id: 101,
    name: "Sita Gita",
    brand: "Krishna Gita",
    price: 129,
    quantity: "1 Box",
    image: "image/9.jpg",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Fancy Shot",
  },
{
    id: 102,
    name: "Dancing Butterfly",
    brand: "MSK",
    price: 110,
    quantity: "1 Box",
    image: "image/WhatsApp Image 2025-10-11 at 17.50.40_c91d791e.jpg",
    description: "1 Box",
    category: "Fancy Items",
  },
{
    id: 103,
    name: "Fancy Helicopter",
    brand: "Vetri",
    price: 169,
    quantity: "1 Box",
    image: "image/28.jpg",
    description: "1 Box",
    category: "Fancy Items",
  },
{
    id: 104,
    name: "Top Spinner",
    brand: "Vetri",
    price: 239,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "1 Box",
    category: "Fancy Items",
  },
{
    id: 105,
    name: "Fancy Drone",
    brand: "Vetri",
    price: 239,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "1 Box",
    category: "Fancy Items",
  },
{
    id: 106,
    name: "Twinkling Star 45cm",
    brand: "Bangaru",
    price: 49,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "1 Box",
    category: "Fancy Items",
  },
{
    id: 107,
    name: "Twinkling Star 120cm",
    brand: "Bangaru",
    price: 110,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "1 Box",
    category: "Fancy Items",
  },
{
    id: 108,
    name: "Ler (50 Wala Deluxe Ler)",
    brand: "ShivJyoti",
    price: 169,
    quantity: "1 Ler",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Ler",
  },
{
    id: 109,
    name: "Ler (24 Wala Deluxe Ler)",
    brand: "ShivJyoti",
    price: 79,
    quantity: "1 Ler",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Ler",
  },
{
    id: 110,
    name: "Ler (24 Wala Deluxe Jungle Ler)",
    brand: "ShivJyoti",
    price: 99,
    quantity: "1 Ler",
    image: "/firecracker.webp",
    description: "A perfect festival combo pack with rockets, chakris, and sparklers.",
    category: "Ler",
  },

];
