// ---------- products.js ----------
// ✅ No "export", only plain JS variable (works in normal HTML setup)

const PRODUCTS = [
  {
    id: 1,
    name: "Rocket Lunic 2 Sound",
    brand: "Shivjothi",
    price: 179,
    quantity: "1 Box",
    image: "image/111.jpg",
    description: "A high-flying, colorful rocket that bursts **twice** with a **loud crackle/sound**.",
    category: "Rockets",
  },
  {
    id: 2,
    name: "Rocket Music Whizling",
    brand: "Shri Vijai",
    price: 269,
    quantity: "1 Box",
    image: "image/1003.jpg",
    description: "A large rocket that **soars with a loud whistling sound** before bursting.",
    category: "Rockets",
  },
  {
    id: 3,
    name: "Lunic Rocket 3 Sound",
    brand: "Nandi",
    price: 349,
    quantity: "1 Box",
    image: "image/24.jpg",
    description: "A high-flying, colorful rocket that bursts **three times** with a **loud crackle/sound**.",
    category: "Rockets",
  },
  {
    id: 4,
    name: "Lunic Rocket Jumbo Bome",
    brand: "Nandi",
    price: 249,
    quantity: "1 Box",
    image: "image/1004.jpg",
    description: "A rocket that **whistles loudly** before bursting with a bang.",
    category: "Rockets",
  },
  {
    id: 5,
    name: "Lunic Rocket Tuffan Queen",
    brand: "Nandi",
    price: 329,
    quantity: "1 Box",
    image: "image/29.jpg",
    description: "A sky rocket known for its **high flight** and **spectacular aerial display**.",
    category: "Rockets",
  },
  {
    id: 6,
    name: "Lunic Rocket",
    brand: "Mugunth",
    price: 189,
    quantity: "1 Box",
    image: "image/1006.jpg",
    description: "A standard rocket designed for a good **vertical flight and aerial burst**.",
    category: "Rockets",
  },
  {
    id: 7,
    name: "Rocket Bome Super",
    brand: "Vaishnavi",
    price: 139,
    quantity: "1 Box",
    image: "image/1007.jpg",
    description: "A high-flying rocket that produces a **very loud bang** upon explosion.",
    category: "Rockets",
  },
  {
    id: 8,
    name: "Rocket Bome",
    brand: "Rajlakshmi",
    price: 110,
    quantity: "1 Box",
    image: "image/1003.jpg",
    description: "A standard rocket that provides a **loud aerial explosion**.",
    category: "Rockets",
  },
  {
    id: 9,
    name: "Lunic Rocket 3 Sound",
    brand: "Shivjothi",
    price: 199,
    quantity: "1 Box",
    image: "image/1009.jpg",
    description: "An extra loud rocket that **blasts three times** upon reaching height.",
    category: "Rockets",
  },
  {
    id: 10,
    name: "Flower Pot Small",
    brand: "Malti",
    price: 110,
    quantity: "1 box",
    image: "image/110.jpg",
    description: "A small fountain creating a **golden shower of sparks** with vibrant trails and sparkle.",
    category: "Anar",
  },
  {
    id: 11,
    name: "Flower Pot Big",
    brand: "Malti",
    price: 135,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "A large, bright cone fountain spreading a **tall display of colorful sparks**.",
    category: "Anar",
  },
  {
    id: 12,
    name: "Flower Pot Ashoka",
    brand: "Nandi",
    price: 399,
    quantity: "1 box",
    image: "image/112.jpg",
    description: "A premium fountain that produces a **long-lasting, multi-color display** for the evening.",
    category: "Anar",
  },
  {
    id: 13,
    name: "Flower Pot Giant",
    brand: "Nandi",
    price: 549,
    quantity: "1 box",
    image: "image/113.jpg",
    description: "A giant fountain with a powerful and varied display of **mixed color flames and star effects**.",
    category: "Anar",
  },
  {
    id: 14,
    name: "Flower Pot Color koti",
    brand: "Mugunth",
    price: 259,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "A medium-sized flower pot featuring a **safe, vivid, and colorful flame** for kids.",
    category: "Anar",
  },
  {
    id: 15,
    name: "Flower Pot Ashoka",
    brand: "Mugunth",
    price: 199,
    quantity: "1 box",
    image: "image/115.jpg",
    description: "A large flower pot with **golden glitter** effects and a loud, continuous **fizzing sound**.",
    category: "Anar",
  },
  {
    id: 16,
    name: "Flower Pot Special",
    brand: "Mugunth",
    price: 149,
    quantity: "1 box",
    image: "image/116.jpg",
    description: "A special edition fountain creating a **silver glittering cascade** for Diwali celebrations.",
    category: "Anar",
  },
  {
    id: 17,
    name: "Flower Pot Special",
    brand: "Malti",
    price: 179,
    quantity: "1 box",
    image: "image/117.jpg",
    description: "A premium cone fountain offering a **long-lasting, special effect display**.",
    category: "Anar",
  },
  {
    id: 18,
    name: "Flower Pot Red and Green",
    brand: "Malti",
    price: 279,
    quantity: "1 box",
    image: "image/118.jpg",
    description: "A vibrant fountain that cycles between **bright red and green colored sparks**.",
    category: "Anar",
  },
  {
    id: 19,
    name: "Flower Pot Colour koti",
    brand: "Malti",
    price: 439,
    quantity: "1 box",
    image: "image/21.jpg",
    description: "A large fountain that projects a **bright neon, multi-color spray**.",
    category: "Anar",
  },
  {
    id: 20,
    name: "Flower Pot Red and White",
    brand: "Nandi",
    price: 279,
    quantity: "1 box",
    image: "image/120.jpg",
    description: "A colorful fountain with alternating **red and white spark effects**.",
    category: "Anar",
  },
  {
    id: 21,
    name: "Flower Pot Special",
    brand: "Nandi",
    price: 259,
    quantity: "1 box",
    image: "/firecracker.webp",
    description: "A special edition fountain known for its **unique effect and colorful spray**.",
    category: "Anar",
  },
  {
    id: 22,
    name: "Fuljhadi 9cm Two in One",
    brand: "Classic",
    price: 29,
    quantity: "1 box",
    image: "image/122.jpg",
    description: "A small sparkler with a **two-in-one effect** (e.g., color change or double sparkle).",
    category: "Fuljhadi",
  },
  {
    id: 23,
    name: "Fuljhadi 10cm",
    brand: "Classic",
    price: 59,
    quantity: "1 box",
    image: "image/123.jpg",
    description: "A standard **10cm sparkler stick** releasing bright, festive sparks.",
    category: "Fuljhadi",
  },
  {
    id: 24,
    name: "Fuljhadi 12cm",
    brand: "Classic",
    price: 69,
    quantity: "1 box",
    image: "image/122.jpg",
    description: "A **12cm sparkler** producing bright silver sparks for night celebrations.",
    category: "Fuljhadi",
  },
  {
    id: 25,
    name: "Fuljhadi 15cm",
    brand: "Classic",
    price: 79,
    quantity: "1 box",
    image: "image/27.jpg",
    description: "A **15cm sparkler** stick. **10 pieces per box**.",
    category: "Fuljhadi",
  },
  {
    id: 26,
    name: "Fuljhadi 30cm",
    brand: "Classic",
    price: 79,
    quantity: "1 box",
    image: "image/26.jpg",
    description: "A **long-lasting 30cm sparkler** stick. **5 pieces per box**.",
    category: "Fuljhadi",
  },
  {
    id: 27,
    name: "Chakkar Deluxe",
    brand: "Blue Star",
    price: 239,
    quantity: "1 Box",
    image: "image/127.jpg",
    description: "A deluxe **circular spinning ground firework** with a vibrant golden sparkle.",
    category: "Chakri",
  },
  {
    id: 28,
    name: "Chakkar Special",
    brand: "Blue Star",
    price: 129,
    quantity: "1 Box",
    image: "image/14.jpg",
    description: "A special **spinning ground firework** producing a bright spiral of flames.",
    category: "Chakri",
  },
  {
    id:  29,
    name: "Chakkar Special",
    brand: "Nandi",
    price: 169,
    quantity: "1 Box",
    image: "image/13.jpg",
    description: "A special edition **ground spinner** with a colorful ring of fire.",
    category: "Chakri",
  },
  {
    id: 30,
    name: "Chakkar Ashoka",
    brand: "Standard",
    price: 149,
    quantity: "1 Box",
    image: "image/130.jpg",
    description: "A classic **ground spinning firework** known for its beautiful color rotation.",
    category: "Chakri",
  },
  {
    id: 31,
    name: "Chakkar Ashoka",
    brand: "Standard",
    price: 149,
    quantity: "1 Box",
    image: "image/130.jpg",
    description: "A classic **ground spinning firework** known for its beautiful color rotation.",
    category: "Chakri",
  },
  {
    id: 32,
    name: "Chakkar Duluxe",
    brand: "Nandi",
    price: 279,
    quantity: "1 Box",
    image: "image/132.jpg",
    description: "A deluxe **heavy-duty ground spinner** that lasts longer and throws higher sparks.",
    category: "Chakri",
  },
  {
    id: 33,
    name: "Ler (2000 Wala Ler)",
    brand: "Mugunth",
    price: 879,
    quantity: "1 Ler",
    image: "image/133.jpg",
    description: "A **garland of 2000 small crackers** that burst in a long, continuous, and deafening chain reaction.",
    category: "Ler",
  },
  {
    id: 34,
    name: "Ler (5000 Wala Ler)",
    brand: "Rajesh",
    price: 2199,
    quantity: "1 Ler",
    image: "image/134.jpg",
    description: "A large **garland of 5000 small crackers** creating a massive, long-duration sound display.",
    category: "Ler",
  },
  {
    id: 35,
    name: "Ler (1000 Wala Ler)",
    brand: "Ganesh Durve",
    price: 749, // corrected
    quantity: "1 Ler",
    image: "/firecracker.webp",
    description: "A **garland of 1000 small crackers** for a continuous, mid-length sound chain.",
    category: "Ler",
  },
{
    id: 36,
    name: "Ler (16 Wala Ler)",
    brand: "Mugunth",
    price: 19,
    quantity: "1 Ler",
    image: "image/136.jpg",
    description: "A small, quick **garland of 16 crackers** for a short burst of noise.",
    category: "Ler",
  },
{
    id: 37,
    name: "Ler (300 Wala Ler)",
    brand: "Mugunth",
    price: 179,
    quantity: "1 Ler",
    image: "image/137.jpg",
    description: "A medium **garland of 300 crackers** for a substantial sound duration.",
    category: "Ler",
  },

{
    id: 38,
    name: "30 Shot",
    brand: "Jawa",
    price: 879,
    quantity: "1 Box",
    image: "image/5.jpg",
    description: "A **30-shot aerial cake** that launches multiple colorful bursts into the sky.",
    category: "Fancy Shot",
  },
{
    id: 39,
    name: "12 Shot",
    brand: "Jawa",
    price: 269,
    quantity: "1 Box",
    image: "image/18.jpg",
    description: "A **12-shot aerial cake** launching multiple bursts of color and sound.",
    category: "Fancy Shot",
  },
{
    id: 40,
    name: "7 Shot",
    brand: "Nandi",
    price: 159,
    quantity: "1 Box",
    image: " image/140.jpg",
    description: "A **7-shot aerial cake** that fires seven colorful bursts in quick succession.",
    category: "Fancy Shot",
  },
{
    id: 41,
    name: "7 Shot Stalin",
    brand: "UV Box",
    price: 179,
    quantity: "1 Box",
    image: "image/141.jpg",
    description: "A **7-shot aerial cake** known for its powerful Stalin-style bursts.",
    category: "Fancy Shot",
  },
{
    id: 42,
    name: "12 Shot",
    brand: "Pravin",
    price: 329,
    quantity: "1 Box",
    image: "image/23.jpg",
    description: "A **12-shot aerial cake** providing a vibrant sequence of aerial effects.",
    category: "Fancy Shot",
  },
{
    id: 43,
    name: "Small Fancy 5 ka Dum",
    brand: "Blue Star",
    price: 299,
    quantity: "1 Box",
    image: "image/WhatsApp Image 2025-10-11 at 17.49.32_9dbce41e.jpg",
    description: "A small fancy box with **5 distinct aerial effects** for a quick show.",
    category: "Fancy Shot",
  },
{
    id: 44,
    name: "2 inch Fancy",
    brand: "Jawa",
    price: 220,
    quantity: "1 Box",
    image: "image/144.jpg",
    description: "A standard **2-inch single-shot aerial shell** with a brilliant burst.",
    category: "Fancy Shot",
  },
  {
    id: 45,
    name: "2 inch Fancy",
    brand: "Jawa",
    price: 169,
    quantity: "1 Box",
    image: "image/145.jpg",
    description: "A standard **2-inch single-shot aerial shell** with a brilliant burst.",
    category: "Fancy Shot",
  },
{
    id: 46,
    name: "1 inch Chota Fancy",
    brand: "Jawa",
    price: 89,
    quantity: "1 Box",
    image: "image/146.jpg",
    description: "A small **1-inch aerial shell** for a modest but vibrant aerial burst.",
    category: "Shot",
  },
{
    id: 47,
    name: "2 inch Fancy 3D",
    brand: "Geeta Krishna",
    price: 329,
    quantity: "1 Box",
    image: "image/147.jpg",
    description: "A **2-inch aerial shell** with a **special 3D-effect** burst (e.g., crackling or distinct shape).",
    category: "Fancy Shot",
  },

{
    id: 48,
    name: "2 inch Fancy 3 in 1",
    brand: "Aayan",
    price: 329,
    quantity: "1 Box",
    image: "image/148.jpg",
    description: "A **2-inch aerial shell** that produces **three different effects** in a single launch.",
    category: "Fancy Shot",
  },

{
    id: 49,
    name: "2 inch Fancy",
    brand: "Aayan",
    price: 110,
    quantity: "1 Box",
    image: "image/149.jpg",
    description: "A standard **2-inch single-shot aerial shell** with a good aerial burst.",
    category: "Fancy Shot",
  },
{
    id: 50,
    name: "2 inch Fancy 3D",
    brand: "Blue Star",
    price: 659,
    quantity: "1 Box",
    image: "image/150.jpg",
    description: "A premium **2-inch aerial shell** with a powerful **3D-effect** burst.",
    category: "Fancy Shot",
  },
{
    id: 51,
    name: "Chota Fancy 5 in 1",
    brand: "Blue Star",
    price: 549,
    quantity: "1 Box",
    image: "image/151.jpg",
    description: "A small aerial cake featuring **5 different effects** in one continuous show.",
    category: "Fancy Shot",
  },
{
    id: 52,
    name: "Small Fancy Astro Boy 5 in 1",
    brand: "Geet Krishna",
    price: 219,
    quantity: "1 Box",
    image: "image/152.jpg",
    description: "A small, themed aerial cake with **5 unique effects** in its sequence.",
    category: "Fancy Shot",
  },
{
    id: 53,
    name: "60 Shot",
    brand: "Jawa",
    price: 1749,
    quantity: "1 Box",
    image: "image/7.jpg",
    description: "A massive **60-shot aerial cake** providing a long-duration, intense fireworks display.",
    category: "Fancy Shot",
  },

{
    id: 54,
    name: "15 Shot",
    brand: "NSV",
    price: 599,
    quantity: "1 Box",
    image: "image/154.jpg",
    description: "A **15-shot aerial cake** that fires multiple bursts into the sky.",
    category: "Fancy Shot",
  },
{
    id: 55,
    name: "15 Shot",
    brand: "Selon",
    price: 599,
    quantity: "1 Box",
    image: "image/155.jpg",
    description: "A **15-shot aerial cake** providing a vibrant sequence of aerial bursts.",
    category: "Fancy Shot",
  },
{
    id: 56,
    name: "3 inch Payli",
    brand: "NSV",
    price: 999,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A **3-inch shell (Payli)** that launches a single, very high, and grand aerial burst.",
    category: "Fancy Shot",
  },
{
    id: 57,
    name: "4 inch Payli",
    brand: "NSV",
    price: 1299,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A **4-inch shell (Payli)** for an extremely high and large single aerial explosion.",
    category: "Fancy Shot",
  },
{
    id: 58,
    name: "4 inch Payli",
    brand: "NSV",
    price: 1299,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A **4-inch shell (Payli)** for an extremely high and large single aerial explosion.",
    category: "Fancy Shot",
  },
{
    id: 59,
    name: "Air Super Sonic Bome",
    brand: "Nandi",
    price: 159,
    quantity: "1 Box",
    image: "image/12.jpg",
    description: "A powerful bomb that creates an **ultra-loud, supersonic bang**.",
    category: "Bome",
  },
{
    id: 60,
    name: "Air Super Sonic Bome",
    brand: "Bandukwala",
    price: 159,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A powerful bomb that creates an **ultra-loud, supersonic bang**.",
    category: "Bome",
  },
{
    id: 61,
    name: "Mirchi Bome Super Duplex",
    brand: "Bandukwala",
    price: 239,
    quantity: "1 Box",
    image: "image/17.jpg",
    description: "A **'Mirchi' (chili) shaped bomb** with a super loud, duplex (double) explosion.",
    category: "Bome",
  },
{
    id: 62,
    name: "Parrote Bome",
    brand: "Bandukwala",
    price: 69,
    quantity: "1 Pack",
    image: "image/162.jpg",
    description: "A small, quick cracker known as a **'Parrot' bomb** for a sharp, mid-level bang.",
    category: "Bome",
  },
{
    id: 63,
    name: "Laxmi Bome Medium Size",
    brand: "Nandi",
    price: 59,
    quantity: "1 Pack",
    image: "image/163.jpg",
    description: "A **medium-sized 'Laxmi' bomb** known for its moderately loud and distinct bang.",
    category: "Bome",
  },
{
    id: 64,
    name: "Parrote Bome",
    brand: "ARD",
    price: 59,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A small, quick cracker known as a **'Parrot' bomb** for a sharp, mid-level bang.",
    category: "Bome",
  },
{
    id: 65,
    name: "Hathi Bome",
    brand: "Nandi",
    price: 79,
    quantity: "1 Pack",
    image: "image/165.jpg",
    description: "A moderately loud **'Hathi' (Elephant) bomb** for a robust sound effect.",
    category: "Bome",
  },
{
    id: 66,
    name: "Two Sound Bome",
    brand: "Nandi",
    price: 79,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A single bomb that produces **two distinct, loud crackles** in quick succession.",
    category: "Bome",
  },
{
    id: 67,
    name: "Two Sound Bome",
    brand: "ARD",
    price: 99,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A single bomb that produces **two distinct, loud crackles** in quick succession.",
    category: "Bome",
  },
{
    id: 68,
    name: "Bullet Bome",
    brand: "Ganeshwari",
    price: 39,
    quantity: "1 Box",
    image: "image/169.jpg",
    description: "A small, sharp cracker known as a **'Bullet' bomb** for a quick, focused bang.",
    category: "Bome",
  },
{
    id: 69,
    name: "Bullet Bome",
    brand: "Aman",
    price: 59,
    quantity: "1 Box",
    image: "image/168.jpg",
    description: "A small, sharp cracker known as a **'Bullet' bomb** for a quick, focused bang.",
    category: "Bome",
  },
{
    id: 70,
    name: "King Kong",
    brand: "Nandi",
    price: 229,
    quantity: "1 Box",
    image: "image/170.jpg",
    description: "A large, **extra-powerful bomb** known for its enormous and thunderous explosion.",
    category: "Bome",
  },
{
    id: 71,
    name: "Alwin Bome",
    brand: "Nandi",
    price: 199,
    quantity: "1 Box",
    image: "image/171.jpg",
    description: "A medium-to-large bomb that produces a **deep and resounding bang**.",
    category: "Bome",
  },
{
    id: 72,
    name: "Commander Atom Bome",
    brand: "Jayhind",
    price: 219,
    quantity: "1 Box",
    image: "image/15.jpg",
    description: "A powerful **'Atom' bomb** cracker with a sharp and commanding explosion.",
    category: "Bome",
  },
{
    id: 73,
    name: "Tehelka Atom Bome",
    brand: "Jayhind",
    price: 279,
    quantity: "1 Box",
    image: "image/173.jpg",
    description: "A very loud **'Tehelka' (Uproar) Atom Bomb** designed for maximum volume.",
    category: "Bome",
  },
{
    id: 74,
    name: "Jolly Bome",
    brand: "Nandi",
    price: 259,
    quantity: "1 Box",
    image: "image/11.jpg",
    description: "A fun bomb cracker known for its **distinctive sound and festive packaging**.",
    category: "Bome",
  },
{
    id: 75,
    name: "Korona Bome",
    brand: "Aayan",
    price: 379,
    quantity: "1 Box",
    image: "image/10.jpg",
    description: "A large, powerful bomb with a **deep and resonating explosion**.",
    category: "Bome",
  },
{
    id: 76,
    name: "Red Bijali Loose ",
    brand: "Aman",
    price: 39,
    quantity: "1 Pack",
    image: "image/176.jpg",
    description: "A pack of **small, quick-fire 'Red Bijali' (Electric) crackers**. **50 pieces per pack**.",
    category: "Child Items",
  },
{
    id: 77,
    name: "Red Bijali Loose ",
    brand: "Nandi",
    price: 59,
    quantity: "1 Pack",
    image: "image/177.jpg",
    description: "A pack of **small, quick-fire 'Red Bijali' (Electric) crackers**. **50 pieces per pack**.",
    category: "Child Items",
  },
{
    id: 78,
    name: "Red Bijali Loose ",
    brand: "Aman",
    price: 49,
    quantity: "1 Pack",
    image: "image/178.jpg",
    description: "A pack of **small, quick-fire 'Red Bijali' (Electric) crackers**. **100 pieces per pack**.",
    category: "Child Items",
  },
{
    id: 79,
    name: "Laxmi Bome Large Size",
    brand: "Nandi",
    price: 69,
    quantity: "1 Pack",
    image: "image/179.jpg",
    description: "A **large-sized 'Laxmi' bomb** known for its moderately loud and distinct bang.",
    category: "Bome",
  },
{
    id: 80,
    name: "Spring Gun",
    brand: "Matchbox",
    price: 49,
    quantity: "1 Pcs",
    image: "image/25.jpg",
    description: "A fun toy gun that uses caps for a **small pop sound**.",
    category: "Child Items",
  },
{
    id: 81,
    name: "Roll Gun",
    brand: "Roll",
    price: 20,
    quantity: "1 Pcs",
    image: "image/rollgun.jpg",
    description: "A toy gun that uses **roll caps** for a continuous, rapid-fire popping sound.",
    category: "Child Items",
  },
{
    id: 82,
    name: "Small Missile Gun",
    brand: "Roll",
    price: 29,
    quantity: "1 Pcs",
    image: "image/Small Gun.jpg",
    description: "A small toy gun designed to shoot **plastic missiles** (non-pyrotechnic).",
    category: "Child Items",
  },
{
    id: 83,
    name: "Big Missile Gun",
    brand: "Roll",
    price: 59,
    quantity: "1 Pcs",
    image: "image/smallgun.jpg",
    description: "A large toy gun designed to shoot **plastic missiles** (non-pyrotechnic).",
    category: "Child Items",
  },
{
    id: 84,
    name: "Ler (28 Wala Ler)",
    brand: "Mugunth",
    price: 29,
    quantity: "1 Ler",
    image: "image/184.jpg",
    description: "A short **garland of 28 crackers** for a quick sound sequence.",
    category: "Ler",
  },
{
    id: 85,
    name: "Ring Cap",
    brand: "Sony",
    price: 15,
    quantity: "1 Pcs",
    image: "image/WhatsApp Image 2025-10-11 at 17.50.10_171766aa.jpg",
    description: "A packet of **toy gun ring caps** for loud popping sounds.",
    category: "Child Items",
  },
{
    id: 86,
    name: "Mitthu Bome",
    brand: "Blue Star",
    price: 19,
    quantity: "1 Pack",
    image: "/firecracker.webp",
    description: "A very small, mild bomb cracker, often called a **'Mitthu' (Parrot) bomb**.",
    category: "Bome",
  },
{
    id: 87,
    name: "Mataka Genie",
    brand: "Timtim",
    price: 259,
    quantity: "1 box",
    image: "image/3.jpg",
    description: "A large, earthen-pot shaped fountain that produces **golden glitter and a fizzing sound**.",
    category: "Anar",
  },
{
    id: 88,
    name: "Mataka Star Gudiya",
    brand: "Timtim",
    price: 299,
    quantity: "1 box",
    image: "image/2.jpg",
    description: "A large, earthen-pot shaped fountain known for its **star-shaped sparks**.",
    category: "Anar",
  },
{
    id: 89,
    name: "Mataka Mini Pearl Gudiya", // corrected typo
    brand: "Timtim",
    price: 259,
    quantity: "1 box",
    image: "image/WhatsApp Image 2025-10-11 at 17.53.42_8e84cbc6.jpg",
    description: "A mini, earthen-pot shaped fountain that creates a **showering 'pearl' effect**.",
    category: "Anar",
  },
{
    id: 90,
    name: "Rocket Baby Pearl",
    brand: "Rajlaxmi",
    price: 69,
    quantity: "1 Box",
    image: "image/16.jpg",
    description: "A small-sized rocket that launches and bursts with a **soft 'pearl' light effect**.",
    category: "Rockets",
  },
{
    id: 91,
    name: "KitKat Silsila",
    brand: "Blue Star",
    price: 59,
    quantity: "1 Pack",
    image: "image/191.jpg",
    description: "A pack of novelty firecrackers with a **silsila (chain) of small crackles**.",
    category: "Child Items",
  },
{
    id: 92,
    name: "KitKat Jee",
    brand: "Blue Star",
    price: 119,
    quantity: "1 Pack",
    image: "image/22.jpg",
    description: "A pack of novelty firecrackers with **unique sound and light effects**.",
    category: "Child Items",
  },
{
    id: 93,
    name: "Roll",
    brand: "Gun Roll",
    price: 99,
    quantity: "1 Box",
    image: "image/193.jpg",
    description: "A box of **paper roll caps** used in roll cap guns.",
    category: "Child Items",
  },
{
    id: 94,
    name: "Missile",
    brand: "Gun Missile",
    price: 20,
    quantity: "1 Box 10 Unit",
    image: "image/194.jpg",
    description: "A box of **plastic missiles** used as toy gun ammunition. **10 units per box**.",
    category: "Child Items",
  },
{
    id: 95,
    name: "Pop-Pop",
    brand: "Pop-pop",
    price: 10,
    quantity: "1 Box",
    image: "image/195.jpg",
    description: "Small, safety **'pop-pop' snaps** that explode when thrown or stomped on.",
    category: "Child Items",
  },
{
    id: 96,
    name: "Dhaga Bome",
    brand: "Fox",
    price: 10,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A small **'Dhaga' (thread) bomb** known for its quick fizz and mild pop.",
    category: "Child Items",
  },
{
    id: 97,
    name: "Machis Bome",
    brand: "Fox",
    price: 20,
    quantity: "1 Box",
    image: "image/197.jpg",
    description: "A **'Matchbox' bomb** designed to ignite by striking it like a safety match.",
    category: "Child Items",
  },
{
    id: 98,
    name: "Photo Flash",
    brand: "Blue Star",
    price: 110,
    quantity: "1 Box",
    image: "image/20.jpg",
    description: "A firework that produces a **single, brilliant flash of white light** (like a camera flash).",
    category: "Fancy Items",
  },
{
    id: 99,
    name: "Pencile Golden Light",
    brand: "Blue Star",
    price: 59,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A **'Pencil' fountain** stick that produces a shower of **golden sparks**.",
    category: "Fancy Items",
  },
{
    id: 100,
    name: "Pencile Golden Light",
    brand: "VKR",
    price: 69,
    quantity: "1 Box",
    image: "image/19.jpg",
    description: "A **'Pencil' fountain** stick that produces a shower of **golden sparks**.",
    category: "Fancy Items",
  },
{
    id: 101,
    name: "Sita Gita",
    brand: "Krishna Gita",
    price: 129,
    quantity: "1 Box",
    image: "image/9.jpg",
    description: "A novelty aerial item with **two intertwined effects (Sita & Gita)** for a unique aerial performance.",
    category: "Fancy Shot",
  },
{
    id: 102,
    name: "Dancing Butterfly",
    brand: "MSK",
    price: 110,
    quantity: "1 Box",
    image: "image/WhatsApp Image 2025-10-11 at 17.50.40_c91d791e.jpg",
    description: "A small firework that **flies and spins in the air like a butterfly**.",
    category: "Fancy Items",
  },
{
    id: 103,
    name: "Fancy Helicopter",
    brand: "Vetri",
    price: 169,
    quantity: "1 Box",
    image: "image/28.jpg",
    description: "A ground-based firework that **spins rapidly and lifts off the ground like a helicopter**.",
    category: "Fancy Items",
  },
{
    id: 104,
    name: "Top Spinner",
    brand: "Vetri",
    price: 239,
    quantity: "1 Box",
    image: "image/10004.jpg",
    description: "A robust firework that **spins intensely on the ground** with bright sparks.",
    category: "Fancy Items",
  },
{
    id: 105,
    name: "Fancy Drone",
    brand: "Vetri",
    price: 239,
    quantity: "1 Box",
    image: "image/1005.jpg",
    description: "A novelty item that takes off and **flies with a colorful spinning effect**.",
    category: "Fancy Items",
  },
{
    id: 106,
    name: "Twinkling Star 45cm",
    brand: "Bangaru",
    price: 49,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A **45cm sparkler** that burns with a unique **twinkling or strobing light effect**.",
    category: "Fancy Items",
  },
{
    id: 107,
    name: "Twinkling Star 120cm",
    brand: "Bangaru",
    price: 110,
    quantity: "1 Box",
    image: "/firecracker.webp",
    description: "A very long **120cm sparkler** that burns with a **twinkling or strobing light effect**.",
    category: "Fancy Items",
  },
{
    id: 108,
    name: "Ler (50 Wala Deluxe Ler)",
    brand: "ShivJyoti",
    price: 169,
    quantity: "1 Ler",
    image: "image/1108.jpg",
    description: "A deluxe **garland of 50 crackers** with a robust and continuous sound chain.",
    category: "Ler",
  },
{
    id: 109,
    name: "Ler (24 Wala Deluxe Ler)",
    brand: "ShivJyoti",
    price: 79,
    quantity: "1 Ler",
    image: "image/1109.jpg",
    description: "A deluxe **garland of 24 crackers** with a slightly more powerful sound per crackle.",
    category: "Ler",
  },
{
    id: 110,
    name: "Ler (24 Wala Deluxe Jungle Ler)",
    brand: "ShivJyoti",
    price: 99,
    quantity: "1 Ler",
    image: "image/1110.jpg",
    description: "A **garland of 24 crackers** with an added crackling/hissing effect, creating a 'Jungle' sound.",
    category: "Ler",
  },

];